const carbsColor = "hsl(139, 25%, 25%)";
const fatsColor = "hsl(136, 28%, 45%)";
const proteinColor = "hsl(134, 77%, 72%)";
export const data = [
  {
    date: "AD",
    carbs: 25,
    fats: 75,
    protein: 65,
  },
  {
    date: "AE",
    carbs: 5,
    fats: 143,
    protein: 131,
  },
  {
    date: "AF",
    carbs: 69,
    fats: 9,
    protein: 8,
  },
  {
    date: "AG",
    carbs: 43,
    fats: 175,
    protein: 39,
  },
  {
    date: "AI",
    carbs: 65,
    fats: 151,
    protein: 62,
  },
  {
    date: "AL",
    carbs: 9,
    fats: 122,
    protein: 86,
  },
  {
    date: "AM",
    carbs: 145,
    fats: 84,
    protein: 114,
  },
];

export const smallData = [
  {
    date: "Monday",
    degress: 59,
  },
  {
    date: "Tuesday",
    degress: 61,
  },
  {
    date: "Wednesday",
    degress: 55,
  },
  {
    date: "Thursday",
    degress: 78,
  },
  {
    date: "Friday",
    degress: 71,
  },
  {
    date: "Saturday",
    degress: 56,
  },
  {
    date: "Sunday",
    degress: 67,
  },
];

export const sampleEntryList = [
  {
    id: "lc8o3iss",
    date: "2023-01-01",
    dateObj: "2023-01-02T00:00:00.000Z",
    exercise: [
      { title: "bicycling", quantity: 30, calories: 238, userInput: "bike" },
    ],
    food: [
      {
        title: "chocolate",
        quantity: 1,
        weight: 7,
        calories: 37.45,
        nutrition: {
          cholesterol: 1.61,
          fiber: 0.24,
          potassium: 26.04,
          protein: 0.54,
          saturatedFat: 1.3,
          sodium: 5.53,
          sugars: 3.61,
          carbohydrates: 4.16,
          fat: 2.08,
        },
      },
      {
        title: "hazelnut",
        quantity: 1,
        weight: 28.35,
        calories: 183.14,
        nutrition: {
          cholesterol: 0,
          fiber: 2.66,
          potassium: 214.04,
          protein: 4.26,
          saturatedFat: 1.28,
          sodium: 0,
          sugars: 1.39,
          carbohydrates: 4.99,
          fat: 17.69,
        },
      },
      {
        title: "coleslaw",
        quantity: 0.5,
        weight: 109.5,
        calories: 174.11,
        nutrition: {
          cholesterol: 8.76,
          fiber: 2.08,
          potassium: 167.54,
          protein: 0.96,
          saturatedFat: 2.09,
          sodium: 242,
          sugars: 10.45,
          carbohydrates: 13.52,
          fat: 12.9,
        },
      },
      {
        title: "pulled pork",
        quantity: 1,
        weight: 249,
        calories: 418.32,
        nutrition: {
          cholesterol: 87.15,
          fiber: 2.99,
          potassium: 759.45,
          protein: 32.84,
          saturatedFat: 3.53,
          sodium: 1658.34,
          sugars: 37.85,
          carbohydrates: 46.66,
          fat: 11.01,
        },
      },
      {
        title: "sandwich",
        quantity: 2,
        weight: 58,
        calories: 154.86,
        nutrition: {
          cholesterol: 0,
          fiber: 2.32,
          potassium: 102.66,
          protein: 6.22,
          saturatedFat: 0.45,
          sodium: 294.64,
          sugars: 3.43,
          carbohydrates: 28.23,
          fat: 1.88,
        },
      },
      {
        title: "eggs",
        quantity: 3,
        weight: 150,
        calories: 214.5,
        nutrition: {
          cholesterol: 558,
          fiber: 0,
          potassium: 207,
          protein: 18.84,
          saturatedFat: 4.69,
          sodium: 213,
          sugars: 0.56,
          carbohydrates: 1.08,
          fat: 14.27,
        },
      },
    ],
  },
  {
    id: "lc8o0bdj",
    date: "2022-12-31",
    dateObj: "2023-01-01T00:00:00.000Z",
    exercise: [],
    food: [
      {
        title: "cashews",
        quantity: 0.5,
        weight: 68.5,
        calories: 393.19,
        nutrition: {
          cholesterol: 0,
          fiber: 2.06,
          potassium: 387.03,
          protein: 10.49,
          saturatedFat: 6.27,
          sodium: 438.4,
          sugars: 3.43,
          carbohydrates: 22.39,
          fat: 31.75,
        },
      },
      {
        title: "onion",
        quantity: 1,
        weight: 225,
        calories: 99,
        nutrition: {
          cholesterol: 0,
          fiber: 3.15,
          potassium: 373.5,
          protein: 3.06,
          saturatedFat: 0.07,
          sodium: 6.75,
          sugars: 10.64,
          carbohydrates: 22.84,
          fat: 0.43,
        },
      },
      {
        title: "portobello mushroom",
        quantity: 1,
        weight: 121,
        calories: 35.09,
        nutrition: {
          cholesterol: 0,
          fiber: 2.66,
          potassium: 528.77,
          protein: 3.97,
          saturatedFat: 0.08,
          sodium: 13.31,
          sugars: 2.73,
          carbohydrates: 5.37,
          fat: 0.7,
        },
      },
      {
        title: "pineapple",
        quantity: 1,
        weight: 165,
        calories: 82.5,
        nutrition: {
          cholesterol: 0,
          fiber: 2.31,
          potassium: 179.85,
          protein: 0.89,
          saturatedFat: 0.01,
          sodium: 1.65,
          sugars: 16.25,
          carbohydrates: 21.65,
          fat: 0.2,
        },
      },
      {
        title: "carrots",
        quantity: 1,
        weight: 156,
        calories: 54.6,
        nutrition: {
          cholesterol: 0,
          fiber: 4.68,
          potassium: 366.6,
          protein: 1.19,
          saturatedFat: 0.05,
          sodium: 90.48,
          sugars: 5.38,
          carbohydrates: 12.82,
          fat: 0.28,
        },
      },
      {
        title: "celery",
        quantity: 1,
        weight: 101,
        calories: 16.16,
        nutrition: {
          cholesterol: 0,
          fiber: 1.62,
          potassium: 262.6,
          protein: 0.7,
          saturatedFat: 0.04,
          sodium: 80.8,
          sugars: 1.35,
          carbohydrates: 3,
          fat: 0.17,
        },
      },
      {
        title: "quinoa",
        quantity: 1,
        weight: 185,
        calories: 222,
        nutrition: {
          cholesterol: 0,
          fiber: 5.18,
          potassium: 318.2,
          protein: 8.14,
          saturatedFat: 0.43,
          sodium: 12.95,
          sugars: 1.61,
          carbohydrates: 39.41,
          fat: 3.55,
        },
      },
      {
        title: "peanut butter",
        quantity: 3,
        weight: 48,
        calories: 282.24,
        nutrition: {
          cholesterol: 0,
          fiber: 2.74,
          potassium: 284.16,
          protein: 10.53,
          saturatedFat: 4.57,
          sodium: 228.48,
          sugars: 3.12,
          carbohydrates: 11.51,
          fat: 23.78,
        },
      },
    ],
  },
  {
    id: "lc8nzrku",
    date: "2022-12-30",
    dateObj: "2022-12-31T00:00:00.000Z",
    exercise: [],
    food: [
      {
        title: "steel cut oats",
        quantity: 0.5,
        weight: 80,
        calories: 303.2,
        nutrition: {
          cholesterol: 0,
          fiber: 8.08,
          potassium: 289.6,
          protein: 10.52,
          saturatedFat: 0.89,
          sodium: 4.8,
          sugars: 0.79,
          carbohydrates: 54.16,
          fat: 5.22,
        },
      },
      {
        title: "yogurt",
        quantity: 1,
        weight: 170,
        calories: 107.1,
        nutrition: {
          cholesterol: 10.2,
          fiber: 0,
          potassium: 397.8,
          protein: 8.93,
          saturatedFat: 1.7,
          sodium: 119,
          sugars: 11.97,
          carbohydrates: 11.97,
          fat: 2.64,
        },
      },
      {
        title: "walnuts",
        quantity: 3,
        weight: 19.55,
        calories: 127.84,
        nutrition: {
          cholesterol: 0,
          fiber: 1.31,
          potassium: 86.2,
          protein: 2.98,
          saturatedFat: 1.2,
          sodium: 0.39,
          sugars: 0.51,
          carbohydrates: 2.68,
          fat: 12.75,
        },
      },
      {
        title: "chia seeds",
        quantity: 1,
        weight: 12,
        calories: 58.32,
        nutrition: {
          cholesterol: 0,
          fiber: 4.13,
          potassium: 48.84,
          protein: 1.98,
          saturatedFat: 0.4,
          sodium: 1.92,
          sugars: null,
          carbohydrates: 5.05,
          fat: 3.69,
        },
      },
      {
        title: "craisins",
        quantity: 1,
        weight: 10,
        calories: 30.8,
        nutrition: {
          cholesterol: 0,
          fiber: 0.53,
          potassium: 4.9,
          protein: 0.02,
          saturatedFat: 0.01,
          sodium: 0.5,
          sugars: 7.26,
          carbohydrates: 8.28,
          fat: 0.11,
        },
      },
    ],
  },
  {
    id: "lc8nuod8",
    date: "2022-12-29",
    dateObj: "2022-12-29T05:43:42.697Z",
    exercise: [],
    food: [
      {
        title: "eggs",
        quantity: 2,
        weight: 100,
        calories: 143,
        nutrition: {
          cholesterol: 372,
          fiber: 0,
          potassium: 138,
          protein: 12.56,
          saturatedFat: 3.13,
          sodium: 142,
          sugars: 0.37,
          carbohydrates: 0.72,
          fat: 9.51,
        },
      },
      {
        title: "banana",
        quantity: 1,
        weight: 118,
        calories: 105.02,
        nutrition: {
          cholesterol: 0,
          fiber: 3.07,
          potassium: 422.44,
          protein: 1.29,
          saturatedFat: 0.13,
          sodium: 1.18,
          sugars: 14.43,
          carbohydrates: 26.95,
          fat: 0.39,
        },
      },
      {
        title: "walnuts",
        quantity: 50,
        weight: 50,
        calories: 327,
        nutrition: {
          cholesterol: 0,
          fiber: 3.35,
          potassium: 220.5,
          protein: 7.62,
          saturatedFat: 3.06,
          sodium: 1,
          sugars: 1.31,
          carbohydrates: 6.86,
          fat: 32.6,
        },
      },
    ],
  },
];
